openapi: "3.0.0"
info:
  title: Account API
  description: This is a Account api which is used to mutate an Account
  version: "1.0.0"

paths:
  /account:
    get:
      summary: Get a list of all Accounts
      operationId: listAccounts
      tags:
        - Account
      responses:
        '200':
          description: A list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './shared.yaml#/components/schemas/Error'
    post:
      summary: Create an Account object
      operationId: createAccount
      tags:
        - Account
      requestBody:
        description: Account to Add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountReference'
      responses:
        '201':
          description: Account created
          headers:
            Location:
              description: Id of created account
              schema:
                type: integer
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './shared.yaml#/components/schemas/Error'
components:
  schemas:
    Account:
      type: object
      required:
        - User
        - Cards
      properties:
        User:
          $ref: './userDefinition.yaml#/components/schemas/User'
        Cards:
          $ref: './cardDefinition.yaml#/components/schemas/Cards'
    AccountReference:
      type: object
      required:
        - UserId
      properties:
        UserId:
          type: integer

