openapi: "3.0.0"
info:
  title: Account API
  description: This is a Account api which is used to mutate an Account
  version: "1.0.0"

paths:
  /account:
    get:
      summary: Get a list of all Accounts
      operationId: listAccounts
      tags:
        - Account
      responses:
        '200':
          description: A list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './shared.yaml#/components/schemas/Error'
    post:
      summary: Create an Account object
      operationId: createAccount
      tags:
        - Account
      requestBody:
        description: Account to Add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountCreate'
      responses:
        '201':
          description: Account created
          headers:
            Location:
              description: URI of the created resource
              schema:
                type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './shared.yaml#/components/schemas/Error'
components:
  schemas:
    Account:
      type: object
      required:
        - User
        - Cards
      properties:
        User:
          type: object
          properties:
            uuid:
              type: string
            name:
              type: string
        Cards:
          type: array
          items:
            type: object  # Specify the type of elements in the array
            properties:
              id:
                type: string
              cardNumber:
                type: string
    AccountCreate:
      type: object
      required:
        - UserUUID
      properties:
        UserUUID:
          type: string

