openapi: "3.0.0"
info:
  title: Card API
  description: This is a Card api which is used to mutate Cards$
  version: "1.0.0"

paths:
  /card:
    get:
      summary: Get a list of all cards
      operationId: listCards
      tags:
        - Card
      responses:
        '200':
          description: A list of Cards
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Card'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './shared.yaml#/components/schemas/Error'
    post:
      summary: Create a Card object
      operationId: createCard
      tags:
        - Card
      requestBody:
        description: User to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardCreate'
      responses:
        '201':
          description: Card created
          headers:
            Location:
              description: URI of the created resource
              schema:
                type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './shared.yaml#/components/schemas/Error'
components:
  schemas:
    Card:
      type: object
      required:
        - uuid
        - cardNumber
      properties:
        uuid:
          type: string
        cardNumber:
          type: string

    Cards:
      type: array
      items:
        $ref: "#/components/schemas/Card"  # Reference to the Card schema

    CardCreate:
      type: object
      required:
        - cardNumber
      properties:
        cardNumber:
          type: string

