openapi: "3.0.0"
info:
  title: User API
  description: This is a User API which has methods to mutate Users
  version: "1.0.0"

paths:
  /users:
    get:
      summary: List of all Users
      operationId: listUsers
      tags:
        - User
      parameters:
        - name: limit
          in: query
          description: Maximum number of results to return
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: A paged array of Users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './shared.yaml#/components/schemas/Error'
    post:
      summary: Create a User
      operationId: createUser
      tags:
        - User
      requestBody:
        description: User to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '201':
          description: User created
          headers:
            Location:
              description: URI of the created resource
              schema:
                type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: './shared.yaml#/components/schemas/Error'

  /users/{userId}:
    get:
      summary: Info for a specific User
      operationId: showUserById
      tags:
        - User
      parameters:
        - name: userId
          in: path
          description: The ID of the User to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: './shared.yaml#/components/schemas/Error'

components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    UserCreate:
      type: object
      required:
        - name
        - password
      properties:
        name:
          type: string
        password:
          type: string
          minLength: 8
          maxLength: 45
          pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*_=+-]).{8,45}$"
